fixing a bunch of syntax errors; replacing single quotes with double to parse vars in the sed commands
Signed-off-by: Christopher Collins <collins.christopher@gmail.com>

diff --git a/cowrie.run.j2 b/cowrie.run.j2
--- a/cowrie.run.j2
+++ b/cowrie.run.j2
@@ -43,14 +43,14 @@ setup_cowrie_conf () {
   cp cowrie.cfg.dist cowrie.cfg
 
   sed -i "s/hostname = svr04/hostname = server/g" cowrie.cfg
-  sed -i 's/#listen_port = 2222/listen_port = ${ssh_port}/g' cowrie.cfg
-  sed -i 's/ssh_version_string = SSH-2.0-OpenSSH_6.0p1 Debian-4+deb7u2/ssh_version_string = SSH-2.0-OpenSSH_6.7p1 Ubuntu-5ubuntu1.3/g' cowrie.cfg
-  sed -i 's/#\[output_hpfeeds\]/[output_hpfeeds]/g' cowrie.cfg
+  sed -i "s/#listen_port = 2222/listen_port = ${ssh_port}/g" cowrie.cfg
+  sed -i "s/ssh_version_string = SSH-2.0-OpenSSH_6.0p1 Debian-4+deb7u2/ssh_version_string = SSH-2.0-OpenSSH_6.7p1 Ubuntu-5ubuntu1.3/g" cowrie.cfg
+  sed -i "s/#\[output_hpfeeds\]/[output_hpfeeds]/g" cowrie.cfg
   sed -i "s/#server = hpfeeds.mysite.org/server = ${server}/g" cowrie.cfg
   sed -i "s/#port = 10000/port = ${server_port}/g" cowrie.cfg
   sed -i "s/#identifier = abc123/identifier = ${uid}/g" cowrie.cfg
   sed -i "s/#secret = secret/secret = ${secret}/g" cowrie.cfg
-  sed -i 's/#debug=false/debug=${debug}/' cowrie.cfg
+  sed -i "s/#debug=false/debug=${debug}/" cowrie.cfg
 
   popd
 
@@ -65,10 +65,10 @@ main () {
   fi
 
   local deploy_key=${DEPLOY_KEY:-}
-  local server=${FEEDS_SERVER}:-localhost}
-  local server_port=${FEEDS_SERVER_PORT}:-10000}
-  local json=${COWRIE_JSON}:-cowrie.json}
-  local ssh_port=${SSH_LISTEN_PORT}:-2222}
+  local server=${FEEDS_SERVER:-localhost}
+  local server_port=${FEEDS_SERVER_PORT:-10000}
+  local json=${COWRIE_JSON:-cowrie.json}
+  local ssh_port=${SSH_LISTEN_PORT:-2222}
 
   local debug=${DEBUG:-false}
 
@@ -80,24 +80,30 @@ main () {
     
   if [[ ! -f ${json} ]]
   then
-    register ${deploy_key} ${server_url} ${cowrie_json} \
-      || echo "Failed to register with ${server_url} using key: ${deploy_key}" \
-      && exit 1
+    register ${deploy_key} ${server} ${json}
+
+    return=$?
+    
+    if [[ $return -ne 0 ]]
+    then
+      echo "Failed to register with ${server} using key: ${deploy_key}"
+      exit 1
+    fi
   fi
   
-  local uuid=$(python -c "import json;obj=json.load(file(${json}));print obj['uuid']")
+  local uuid=$(python -c "import json;obj=json.load(file('${json}'));print obj['uuid']")
 
   if [ -z "$uuid" ]
   then
-    echo "Could not create sensor using name \"$hostname\"."
+    echo "Could not create sensor using name \"$(hostname -f)\"."
     exit 1
   else
     echo "Created sensor: " $uuid
   fi
 
   local server=$(echo $server | sed 's#^http://##; s#^https://##; s#/.*$##; s/:.*$//')
-  local uid=$(python -c 'import json;obj=json.load(file("${json}"));print obj["identifier"]')
-  local secret=$(python -c 'import json;obj=json.load(file("${json}"));print obj["secret"]')
+  local uid=$(python -c "import json;obj=json.load(file('${json}'));print obj['identifier']")
+  local secret=$(python -c "import json;obj=json.load(file('${json}'));print obj['secret']")
   
   setup_cowrie_conf ${server} \
                     ${server_port} \
